### ISSUE TITLE
can't connect to websites because of proxy

### ISSUE THREAD

**Issue by tobei** [keithws/node-ssllabs#1]
Is it possible to make it work behind a corporate proxy ? by setting a parameters in the options or just by honoring process.env.http_proxy / process.env.https_proxy if those are set?

**Comment by keithws** [comment]
I had not considered that, but yes, there should be a way to specify a proxy.

Considering the security issues mentioned in HTTPoxy, I think it should use the CGI_HTTP_PROXY environment variable.

**Comment by keithws** [comment]
As of v1.1.0, a.k.a. b2d093cdb7a2a97a90e721e86ab61a10c21b7291, this library will honor the HTTPS_PROXY environment variable.
